name: Java Continuous Integration

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: debugging stuff
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    
      - name: checkout repositoryAdd commentMore actions
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name: Debug Maven Build
        run: |
          cat .github/settings.xml
          mvn --batch-mode clean install --settings .github/settings.xml
        env:
          MAIN_GITHUB_RELEASE_USERNAME: ${{ secrets.MAIN_GITHUB_RELEASE_USERNAME }}
          MAIN_GITHUB_RELEASE_TOKEN: ${{ secrets.MAIN_GITHUB_RELEASE_TOKEN }}
       
