name: Java Continuous Integration

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: debugging stuff
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          java-package: 'jdk'
          cache: 'maven'     
          
      - name: Debug Maven Build
        run: |
          cat .github/settings.xml
          echo ${MAIN_GITHUB_RELEASE_USERNAME}
          echo ${MAIN_GITHUB_RELEASE_TOKEN}
          mvn --batch-mode clean install -Dusername=$GITHUB_ACCESS_TOKEN --settings .github/settings.xml
        env:
          MAIN_GITHUB_RELEASE_USERNAME: ${{ secrets.NAME }}
          MAIN_GITHUB_RELEASE_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.TOKEN }}
       
