name: Java Continuous Integration

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: debugging stuff
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Debug Maven Build
        run: |
          cat .github/settings.xml
          mvn --batch-mode clean install --settings .github/settings.xml
       
